apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arbeidsgiver-altinn-tilganger
  namespace: fager
  labels:
    team: fager
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{{ image }}}

  liveness:
    path: /internal/isalive

  readiness:
    path: /internal/isready

  prometheus:
    enabled: true
    path: /internal/prometheus


  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

  env:
    - name: ALTINN_3_API_BASE_URL
      value: https://platform.altinn.no
    - name: ALTINN_2_BASE_URL
      value: https://www.altinn.no

  envFrom:
    - secret: altinn-tilganger

  azure:
    application:
      enabled: true

  tokenx:
    enabled: true

  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:accessmanagement/authorizedparties.resourceowner"
        - name: "altinn:serviceowner/reportees"

  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: aura
          cluster: prod-gcp
        - application: notifikasjon-bruker-api
        - application: min-side-arbeidsgiver-api
        - application: permitteringsskjema-api
          namespace: permittering-og-nedbemanning
        - application: fritakagp
          namespace: helsearbeidsgiver
        - application: im-altinn
          namespace: helsearbeidsgiver
    outbound:
      external:
        - host: platform.altinn.no
        - host: www.altinn.no

  secureLogs:
    enabled: true

  redis:
    - instance: tilganger
      access: readwrite
